# Version of the Icarus theme that is currently used
version: 2.6.0
# Path or URL to the website's icon
favicon: /images/favicon.svg
# Additional HTML meta tags in an array.
meta: 
# Path or URL to RSS atom.xml
rss: 
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: #/images/logo.svg
    text: Raven's Blog
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    fb_app_id: 
    # Facebook Admin ID
    fb_admins: 
    # Twitter ID
    twitter_id: 
    # Twitter site
    twitter_site: 
    # Google+ profile link
    google_plus: 
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    # Navigation bar links to be shown on the right
    links:
        Email:
            icon: fa fa-envelope
            url: 'mailto:zhang.xingrui@foxmail.com'
        Github:
            icon: fab fa-github
            url: 'https://github.com/ravenxrz'
        bilibili:
            icon: fa fa-video
            url: 'https://space.bilibili.com/26319956'
        netease-clound-music:
            icon: fa fa-music
            url: 'https://music.163.com/#/user/home?id=281439693'
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        Email:
            icon: fa fa-envelope
            url: 'mailto:zhang.xingrui@foxmail.com'
        Github:
            icon: fab fa-github
            url: 'https://github.com/ravenxrz'
        bilibili:
            icon: fa fa-video
            url: 'https://space.bilibili.com/26319956'
        netease-clound-music:
            icon: fa fa-music
            url: 'https://music.163.com/#/user/home?id=281439693'
# Article display settings
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: monokai #atom-one-light
        # Show code copying button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show article thumbnail images
    thumbnail: true
    # Whether to show estimate article reading time
    readtime: true
# Search plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
comment:
    type: gitalk
    owner: ravenxrz         # (required) GitHub user name
    repo: BlogComment          # (required) GitHub repository name
    client_id: b2fd373d2ca2e03e591e     # (required) OAuth application client id
    client_secret: de4ab066908c1fbd32d3a45e091b3538761d685b # (required) OAuth application client secret
    admin: ravenxrz         # (required) GitHub repo owner and collaborators who can initialize github issues
                            #            Can either be a string or an array.
                            #            admin:
                            #                - xxxxxx1
                            #                - xxxxxx2
# Donation entries
# https://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
donate:
    -
        # Donation entry name
        type: alipay
        # Qrcode image URL
        qrcode: '/images/alipay.png'
    -
        # Donation entry name
        type: wechat
        # Qrcode image URL
        qrcode: '/images/wechat.png'
    -
    #     # Donation entry name
    #     type: paypal
    #     # Paypal business ID or email address
    #     business: ''
    #     # Currency code
    #     currency_code: USD
    # -
    #     # Donation entry name
    #     type: patreon
    #     # URL to the Patreon page
    #     url: ''
# Share plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share
share:
    # Share plugin name
    type: 
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # left sidebar settings
    left:
        # Whether the left sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: true
    # right sidebar settings
    right:
        # Whether the right sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: true
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Widget name
        type: profile
        # Where should the widget be placed, left or right
        position: left
        # Author name to be shown in the profile widget
        author: Raven
        # Title of the author to be shown in the profile widget
        author_title: zhang.xingrui@foxmail.com
        # Author's current location to be shown in the profile widget
        location: WuHan
        # Path or URL to the avatar to be shown in the profile widget
        avatar: https://ae01.alicdn.com/kf/HTB1oodRcRCw3KVjSZR0762cUpXaU.png
        # Email address for the Gravatar to be shown in the profile widget
        gravatar: zhang.xingrui@foxmail.com
        # Whether to show avatar image rounded or square
        avatar_rounded: true
        # Path or URL for the follow button
        follow_link: 'https://github.com/ravenxrz'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Email:
                icon: fa fa-envelope
                url: 'mailto:zhang.xingrui@foxmail.com'
            Github:
                icon: fab fa-github
                url: 'https://github.com/ravenxrz'
            Bilibili:
                icon: fa fa-video
                url: 'https://space.bilibili.com/26319956'
            Netease-clound-music:
                icon: fa fa-music
                url: 'https://music.163.com/#/user/home?id=281439693'
    -
        # Widget name
        type: toc
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: links
        # Where should the widget be placed, left or right
        position: left
        # Links to be shown in the links widget
        links:
            我的资源: 'https://ravenxrz.ink/resources'
            聚合图床: 'https://www.superbed.cn/'
            regex101: 'https://regex101.com'
            菜鸟工具: 'https://c.runoob.com'
            cloudconvert: 'https://cloudconvert.com'
            iconfont: 'https://www.iconfont.cn'
            processon: 'https://www.processon.com'
    -
        # Widget name
        type: category
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: tagcloud
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: recent_posts
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: archive
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: tag
        # Where should the widget be placed, left or right
        position: right
# Other plugin settings
plugins:
    # Enable page animations
    animejs: true
    # Enable the lightGallery and Justified Gallery plugins
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: true
    # Enable the MathJax plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: true
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    google-analytics:
        # Google Analytics tracking id
        tracking_id: 
    # Baidu Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    baidu-analytics:
        # Baidu Analytics tracking id
        tracking_id: 
    # Hotjar user feedback plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    hotjar:
        # Hotjar site id
        site_id: 
    # Show a loading progress bar at top of the page
    progressbar: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: true
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome
